version: '2'

services:
  api:
    build: ./api/
    ports:
    - "12345:12345"
    links:
      - mongo
    depends_on:
      - mongo
  ws:
    build: ./websocket/
    ports:
    - "23456:23456"
    links:
      - api
  mongo:
    image: mongo:latest
    container_name: mongo 
    volumes:
      - 'mongodb-data:/data/db/mongo'
    ports:
      - '27017:27017'
    command: mongod --smallfiles

volumes:
  mongodb-data: {}
