version: '2'

services:
  api:
    image: golang:1.8.0-alpine
    ports:
      - "12345:12345"
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - '/tmp/ci:/ci'
    command: /ci/api
  ws:
    image: golang:1.8.0-alpine
    ports:
      - "23456:23456"
    links:
      - api
    volumes:
      - '/tmp/ci:/ci'
    command: /ci/websocket
  mongo:
    image: mongo:latest
    container_name: mongo 
    volumes:
      - 'mongodb-data:/data/db/mongo'
    ports:
      - '27017:27017'
    command: mongod --smallfiles

volumes:
  mongodb-data: {}
